services:
  tegola_server:
    build:
      context: ./tegola_server
      dockerfile: Dockerfile
    image: wnsrn4970/backend-tegola_server:latest
    platform: linux/amd64
    container_name: tegola_server
    ports:
      - "8080:8080"
    networks:
      - navigation-network

  valhalla_server:
    build:
      context: ./valhalla_server
      dockerfile: Dockerfile
    platform: linux/amd64
    image: wnsrn4970/backend-valhalla_server:latest
    container_name: valhalla_server
    ports:
      - "8002:8002"

  rust_server:
    build:
      context: ./rust_server
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@172.17.0.1:5432/osm
    image: wnsrn4970/backend-rust_server:latest
    platform: linux/amd64
    container_name: rust_server
    environment:
      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/osm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    depends_on:
      - tegola_server
      - valhalla_server
    networks:
      - navigation-network
    volumes:
      - ./rust_server/src:/app/src
  

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    platform: linux/amd64
    ports:
      - "8081:8081" # NGINX가 외부에 노출될 포트
      - "80:80"
    depends_on:
      - tegola_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # NGINX 설정 파일
    networks:
      - navigation-network

networks:
  navigation-network:
    external: true

